[package]
name = "rpi-os"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["rpi-os-macros", "boot_test"]

[features]
bsp_rpi3 = []

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
bitflags = "2.9.0"
rpi-os-macros = { path = "rpi-os-macros" }
